use sakila; ## join use nane of table to specify 
# List the number of films per category.
SELECT category.name as category_name, COUNT(film_category.film_id) AS number_of_films
FROM category 
JOIN film_category ON category.category_id = film_category.category_id
GROUP BY category.name;

#Retrieve the store ID, city, and country for each store.
select store.store_id, city.city, country.country
from store
join address on store.address_id = address.address_id
join city ON address.city_id = city.city_id
join country ON city.country_id = country.country_id;
 
 # Calculate the total revenue generated by each store in dollars.
select store.store_id, sum(payment.amount) as total_revenue 
FROM store
JOIN inventory ON store.store_id = inventory.store_id
JOIN rental ON inventory.inventory_id = rental.inventory_id
JOIN payment ON rental.rental_id = payment.rental_id
GROUP BY store.store_id;

#Determine the average running time of films for each category.

select category.name as category_name, avg(film.length) as average_length 
from film 
join film_category on film.film_id = film_category.film_id
JOIN category ON film_category.category_id = category.category_id
GROUP BY category.name;


